# Generated by Django 4.2.10 on 2024-02-29 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_people_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='image',
            field=models.TextField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
